config/routes.rb
Mags::Application.routes.draw do
  
  namespace :api do
    namespace :v1 do
      controller :magazines do
        get   ':format/magazines' => :index
        get   ':format/magazine/:magazine_id/issues' => :issues
        get   ':format/magazine/:magazine_id/issue/:id/pages' => :pages, :as => :pages
      end
    end
  end

  resources :magazines do
    resources :issues do
      resources :pages
    end
  end

  get "home/index"
  root :to => "home#index"
  

end

app/models/issue.rb
class Issue < ActiveRecord::Base
  belongs_to :magazine
  has_many :pages, :dependent => :destroy
end

app/controllers/issues_controller.rb
class IssuesController < ApplicationController
  # GET /issues
  # GET /issues.json
  def index
    @magazine = Magazine.find(params[:magazine_id])
    @issues = @magazine.issues

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @issues }
    end
  end

  # GET /issues/1
  # GET /issues/1.json
  def show
    @magazine = Magazine.find(params[:magazine_id])
    @issue = @magazine.issues.where(:id => params[:id]).first

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @issue }
    end
  end

  # GET /issues/new
  # GET /issues/new.json
  def new
    @magazine = Magazine.find(params[:magazine_id])
    @issue = @magazine.issues.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @issue }
    end
  end

  # GET /issues/1/edit
  def edit
    @magazine = Magazine.find(params[:magazine_id])
    @issue = @magazine.issues.where(:id => params[:id]).first
  end

  # POST /issues
  # POST /issues.json
  def create
    @magazine = Magazine.find(params[:magazine_id])
    @issue = @magazine.issues.create(params[:issue])
    @issue.uuid = UUID.new.generate

    respond_to do |format|
      if @issue.save
        format.html { redirect_to magazine_issues_path(@magazine), notice: 'Issue was successfully created.' }
        format.json { render json: @issue, status: :created, location: @issue }
      else
        format.html { render action: "new" }
        format.json { render json: @issue.errors, status: :unprocessable_entity }
      end
    end
  end
  
  # PUT /issues/1
  # PUT /issues/1.json
  def update
    @magazine = Magazine.find(params[:magazine_id])
    @issue = @magazine.issues.find(params[:id])
    
    respond_to do |format|
      if @issue.update_attributes(params[:issue])
        format.html { redirect_to magazine_issue_url(@magazine, @issue), notice: 'Issue was successfully updated.' }        
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @issue.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /issues/1
  # DELETE /issues/1.json
  def destroy
    @issue = Issue.find(params[:id])
    @issue.destroy

    respond_to do |format|
      format.html { redirect_to magazine_issues_url(@magazine) }
      format.json { head :ok }
    end    
  end
end

app/helpers/issues_helper.rb
module IssuesHelper
end

app/views/issues/_form.html.haml
= form_for [@magazine, @issue] do |f|
  -if @issue.errors.any?
    #error_explanation
      %h2= "#{pluralize(@issue.errors.count, "error")} prohibited this issue from being saved:"
      %ul
        - @issue.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :issue_date
    = f.date_select :issue_date, :discard_day => true
  .field
    = f.label :title
    = f.text_field :title
  .actions
    = f.submit 'Save'

app/views/issues/edit.html.haml
%h1 Editing issue

= render 'form'

= link_to 'Back', magazine_issues_path(@magazine)

app/views/issues/index.html.haml
%h1 Listing issues

%table
  %tr
    %th Magazine
    %th Issue date
    %th Title
    %th
    %th
    %th
    %th

  - @issues.each do |issue|
    %tr
      %td= issue.magazine.name
      %td= issue.issue_date
      %td= issue.title
      %td= link_to 'Pages', magazine_issue_pages_path(@magazine, issue)
      %td= link_to 'Edit', edit_magazine_issue_path(@magazine, issue)
      %td= link_to 'Destroy', [@magazine, issue], :confirm => 'Are you sure?', :method => :delete
      %td= link_to 'Download Issue', download_magazine_issues_path(@magazine, issue)

%br

= link_to 'New Issue', new_magazine_issue_path(@magazine)
= link_to 'Back to Magazine List', magazines_path

app/views/issues/new.html.haml
%h1 New issue

= render 'form'

= link_to 'Back', magazines_path

app/views/issues/show.html.haml
%p#notice= notice

%p
  %b Magazine:
  = @issue.magazine.name
%p
  %b Issue date:
  = @issue.issue_date
%p
  %b Title:
  = @issue.title

= link_to 'Edit', edit_magazine_issue_path(@magazine, @issue)
\|
= link_to 'Back', magazine_issues_path(@magazine)