config/routes.rb
Mags::Application.routes.draw do
  
  namespace :api do
    namespace :v1 do
      controller :magazines do
        get   ':format/magazines' => :index
        get   ':format/magazine/:magazine_id/issues' => :issues
        get   ':format/magazine/:magazine_id/issue/:id/pages' => :pages, :as => :pages
      end
    end
  end

  resources :magazines do
    resources :issues do
      resources :pages
    end
  end

  get "home/index"
  root :to => "home#index"
  

end

app/models/magazine.rb
class Magazine < ActiveRecord::Base
  has_many :issues, :dependent => :destroy
  belongs_to :user
end

app/controllers/api/v1/magazines_controller.rb
class Api::V1::MagazinesController < Api::ApiController
  
  def index
    magazines = Magazine.all
    return render_jsend(:magazines => magazines)
  end
  
  def issues
    magazine = Magazine.find(params[:magazine_id])
    if magazine.issues.any?
      return render_jsend(:issues => magazine.issues)      
    end
  end
  
  def pages
    @magazine = Magazine.find(params[:magazine_id])
    @issue = Issue.find(params[:id])
    @pages = @issue.pages.order(:page_number)
    
    if @pages.any?
      return render_jsend(:pages => @pages)      
    end
  end
    
end

app/controllers/magazines_controller.rb
class MagazinesController < ApplicationController
  # GET /magazines
  # GET /magazines.json
  def index
    @magazines = Magazine.all
    
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @magazines }
    end
  end

  # GET /magazines/1
  # GET /magazines/1.json
  def show
    @magazine = Magazine.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @magazine, :include => :issues }
    end
  end

  # GET /magazines/new
  # GET /magazines/new.json
  def new
    @magazine = Magazine.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @magazine }
    end
  end

  # GET /magazines/1/edit
  def edit
    @magazine = Magazine.find(params[:id])
  end

  # POST /magazines
  # POST /magazines.json
  def create
    @magazine = Magazine.new(params[:magazine])
    @magazine.uuid = UUID.new.generate

    respond_to do |format|
      if @magazine.save
        format.html { redirect_to @magazine, notice: 'Magazine was successfully created.' }
        format.json { render json: @magazine, status: :created, location: @magazine }
      else
        format.html { render action: "new" }
        format.json { render json: @magazine.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /magazines/1
  # PUT /magazines/1.json
  def update
    @magazine = Magazine.find(params[:id])

    respond_to do |format|
      if @magazine.update_attributes(params[:magazine])
        format.html { redirect_to @magazine, notice: 'Magazine was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @magazine.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /magazines/1
  # DELETE /magazines/1.json
  def destroy
    @magazine = Magazine.find(params[:id])
    @magazine.destroy

    respond_to do |format|
      format.html { redirect_to magazines_url }
      format.json { head :ok }
    end
  end
end

app/helpers/magazines_helper.rb
module MagazinesHelper
end

app/views/magazines/_form.html.haml
= form_for @magazine do |f|
  -if @magazine.errors.any?
    #error_explanation
      %h2= "#{pluralize(@magazine.errors.count, "error")} prohibited this magazine from being saved:"
      %ul
        - @magazine.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :description
    = f.text_area :description
  .field
    = f.label :publication_date
    = f.date_select :publication_date
  .actions
    = f.submit 'Save'

app/views/magazines/edit.html.haml
%h1 Editing magazine

= render 'form'

= link_to 'Show', @magazine
\|
= link_to 'Back', magazines_path

app/views/magazines/index.html.haml
%h1 Listing magazines

%table
  %tr
    %th Name
    %th Description
    %th Publication date
    %th
    %th
    %th

  - @magazines.each do |magazine|
    %tr
      %td= magazine.name
      %td= magazine.description
      %td= magazine.publication_date
      %td= link_to 'Issues', magazine_issues_path(magazine)
      %td= link_to 'Edit', edit_magazine_path(magazine)
      %td= link_to 'Destroy', magazine, :confirm => 'Are you sure?', :method => :delete

%br

= link_to 'New Magazine', new_magazine_path

app/views/magazines/new.html.haml
%h1 New magazine

= render 'form'

= link_to 'Back', magazines_path

app/views/magazines/show.html.haml
%p#notice= notice

%p
  %b Name:
  = @magazine.name
%p
  %b Description:
  = @magazine.description
%p
  %b Publication date:
  = @magazine.publication_date

= link_to 'Edit', edit_magazine_path(@magazine)
\|
= link_to 'Back', magazines_path