config/routes.rb
Mags::Application.routes.draw do
  
  namespace :api do
    namespace :v1 do
      controller :magazines do
        get   ':format/magazines' => :index
        get   ':format/magazine/:magazine_id/issues' => :issues
        get   ':format/magazine/:magazine_id/issue/:id/pages' => :pages, :as => :pages
      end
    end
  end

  resources :magazines do
    resources :issues do
      resources :pages
    end
  end

  get "home/index"
  root :to => "home#index"
  

end

app/views/pages/_form.html.haml
= form_for [@magazine, @issue, @page] do |f|
  -if @page.errors.any?
    #error_explanation
      %h2= "#{pluralize(@page.errors.count, "error")} prohibited this page from being saved:"
      %ul
        - @page.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :page_number
    = f.number_field :page_number
  .field
    = f.label :content
    = f.text_area :content
  .actions
    = f.submit 'Save'

app/views/pages/edit.html.haml
%h1 Editing page

= render 'form'

= link_to 'Back', magazine_issue_pages_path(@magazine, @issue)

app/views/pages/index.html.haml
%h1 Listing pages

%table
  %tr
    %th Issue
    %th Page number
    %th Content
    %th
    %th
    %th

  - @pages.each do |page|
    %tr
      %td= page.issue.title
      %td= page.page_number
      %td= link_to 'Edit', edit_magazine_issue_page_path(@magazine, @issue, page)
      %td= link_to 'Destroy', [@magazine, @issue, page], :confirm => 'Are you sure?', :method => :delete

%br

= link_to 'New Page', new_magazine_issue_page_path(@magazine, @issue)
= link_to 'Back to Issue List', magazine_issues_path

app/views/pages/new.html.haml
%h1 New page

= render 'form'

= link_to 'Back', magazine_issue_pages_path

app/views/pages/show.html.haml
%p#notice= notice

%p
  %b Issue:
  = @page.issue_id
%p
  %b Page number:
  = @page.page_number
%p
  %b Content:
  = @page.content

= link_to 'Edit', edit_magazine_issue_page_path(@magazine, @issue, @page)
\|
= link_to 'Back', magazine_issue_pages_path(@magazine, @issue)